### ISSUE TITLE
Add Support to Laravel Mix

### ISSUE THREAD

**Issue by chadidi** [mehranrasulian/laravel-elixir-rtl-sass#1]
Are you intrested in adding a version of this package for laravel mix

**Comment by mehrancodes** [comment]
Fortunately, there is no need to do that anymore.
We are using [rtlcss](https://github.com/MohammadYounes/rtlcss) for this package. but using Laravel mix, it is as easy as adding rtlcss as an option to `mix.sass`, `mix.less` or any other preprocessor you would like!!

[As the Laravel documentation says](https://laravel.com/docs/5.4/mix/#postcss):
>PostCSS, a powerful tool for transforming your CSS, is included with Laravel Mix out of the box. By default, Mix leverages the popular Autoprefixer plug-in to automatically apply all necessary CSS3 vendor prefixes. However, you're free to add any additional plug-ins that are appropriate for your application. First, install the desired plug-in through NPM and then reference it in your  webpack.mix.js file:

 ```js
mix.sass('resources/assets/sass/app.scss', 'public/css')
   .options({
        postCss: [
            require('postcss-css-variables')()
        ]
   });
```

Already I'm using the [postcss-rtl](https://www.npmjs.com/package/postcss-rtl) as a postcss plugin which works like a charm!

**Comment by chadidi** [comment]
@mehranrasulian i found this plugin right now named `webpack-rtl-plugin` and i can use it like this .
`import WebpackRTLPlugin from 'webpack-rtl-plugin
mix.webpackConfig({
plugins: [
new WebpackRTLPlugin({
filename: 'style.[contenthash].rtl.css',
options: {},
diffOnly: false,
minify: true,})
]});`
but i really wanna use `rtlcss` so can you help me out i don't know how to use `postcss` as i never worked with it i know that i have to require `rtlcss` but what next i mean where i can place the path to the file i wanna compile and the output. Thanks.

**Comment by mehrancodes** [comment]
@chadidi Sorry for the delay in answering. Do you have this problem yet?
